---
- name: Restart management
  ansible.builtin.command:
    cmd: docker compose restart management
    chdir: /opt/netbird
  changed_when: true

- name: Restart caddy
  ansible.builtin.command:
    cmd: docker compose restart caddy
    chdir: /opt/netbird
  changed_when: true

- name: Restart coturn
  ansible.builtin.command:
    cmd: docker compose restart coturn
    chdir: /opt/netbird
  changed_when: true

- name: Restart Netbird stack
  ansible.builtin.command:
    cmd: docker compose up -d
    chdir: /opt/netbird
  changed_when: true
