all:
  children:
    vpn:
      hosts:
        gw:
          ansible_host: gw.myapp.example.com
          ansible_user: ubuntu
    mailcow:
      hosts:
        mailcow:
          ansible_host: 10.20.1.100
          ansible_user: ubuntu
    gitlab_server:
      hosts:
        gitlab:
          ansible_host: gitlab.myapp.example.com
          ansible_user: ubuntu
    gitlab_runners:
      hosts:
        stage-runner:
          ansible_host: 10.10.2.100
          ansible_user: ubuntu
        prod-runner:
          ansible_host: 10.30.2.100
          ansible_user: ubuntu
    # Все VM-инстансы, на которых установлен node_exporter
    vm_nodes:
      hosts:
        gw:
        mailcow:
        gitlab:
        stage-runner:
    k8s_apps:
      children:
        k8s_apps_stage:
        k8s_apps_prod:
    k8s_apps_stage:
      hosts:
        stage-k8s:
          ansible_connection: local
    k8s_apps_prod:
      hosts:
        prod-k8s:
          ansible_connection: local
