version: "3.4"

services:
    bt6_monolith:
        restart: always
        build:
            context: .
            args:
                GITLAB_HOST: ${GITLAB_HOST}
        container_name: ${SERVICE_NAME}
        env_file:
            - .env.runtime
        volumes:
            - ./src:/src
            - /containers/logs/${SERVICE_NAME}:/src/logs
        ports:
            - "0.0.0.0:${SERVICE_PORT}:${SERVICE_PORT}"
        networks:
            - default

networks:
    default:
        external: true
        name: bt6
